/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;

CREATE TABLE `15m_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `subforo_ID` smallint(6) unsigned default NULL,
  `url` varchar(50) character set utf8 NOT NULL default '',
  `title` varchar(50) character set utf8 NOT NULL default '',
  `descripcion` varchar(255) character set utf8 NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') character set utf8 NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(900) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(900) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_escribir_msg` varchar(900) NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir_msg` varchar(900) NOT NULL default '',
  `limite` tinyint(3) unsigned NOT NULL default '8',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=latin1;
CREATE TABLE `15m_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` smallint(6) NOT NULL default '0',
  `votos_num` mediumint(9) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=1263 DEFAULT CHARSET=latin1;
CREATE TABLE `15m_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` smallint(6) NOT NULL default '0',
  `votos_num` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `foro_ID` (`hilo_ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=10056 DEFAULT CHARSET=latin1;
CREATE TABLE `atlantis_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `url` varchar(50) NOT NULL default '',
  `title` varchar(50) NOT NULL default '',
  `descripcion` varchar(255) NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(255) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(255) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=55 DEFAULT CHARSET=latin1;
CREATE TABLE `atlantis_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` mediumint(9) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=1025 DEFAULT CHARSET=latin1;
CREATE TABLE `atlantis_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` mediumint(9) default '0',
  PRIMARY KEY  (`ID`),
  KEY `foro_ID` (`hilo_ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=8723 DEFAULT CHARSET=latin1;
CREATE TABLE `cargos` (
  `ID` smallint(6) NOT NULL auto_increment,
  `pais` varchar(30) character set utf8 default NULL,
  `cargo_ID` smallint(6) unsigned NOT NULL default '0',
  `asigna` smallint(5) NOT NULL default '7',
  `nombre` varchar(30) character set utf8 NOT NULL default '',
  `nombre_extra` varchar(255) character set utf8 NOT NULL default '',
  `nivel` tinyint(3) NOT NULL default '1',
  `num` smallint(5) NOT NULL default '0',
  `salario` mediumint(9) unsigned NOT NULL default '0',
  `autocargo` enum('true','false') character set utf8 NOT NULL default 'false',
  `elecciones` datetime default NULL,
  `elecciones_electos` tinyint(3) unsigned default NULL,
  `elecciones_cada` smallint(5) unsigned default NULL,
  `elecciones_durante` tinyint(3) unsigned default NULL,
  `elecciones_votan` varchar(999) character set utf8 default NULL,
  PRIMARY KEY  (`ID`),
  KEY `nivel` (`nivel`),
  KEY `nombre` (`nombre`),
  KEY `asigna` (`asigna`),
  KEY `cargo_ID` (`cargo_ID`),
  KEY `pais` (`pais`)
) ENGINE=MyISAM AUTO_INCREMENT=342 DEFAULT CHARSET=latin1;
CREATE TABLE `cargos_users` (
  `ID` bigint(20) NOT NULL auto_increment,
  `cargo_ID` smallint(5) NOT NULL default '0',
  `pais` varchar(30) default NULL,
  `user_ID` mediumint(8) NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `cargo` enum('true','false') NOT NULL default 'false',
  `aprobado` enum('ok','no') NOT NULL default 'ok',
  `nota` decimal(3,1) unsigned NOT NULL default '0.0',
  PRIMARY KEY  (`ID`),
  KEY `cargo` (`cargo`),
  KEY `user_ID` (`user_ID`),
  KEY `cargo_ID` (`cargo_ID`),
  KEY `aprobado` (`aprobado`),
  KEY `pais` (`pais`),
  KEY `nota` (`nota`)
) ENGINE=MyISAM AUTO_INCREMENT=8893 DEFAULT CHARSET=utf8;
CREATE TABLE `cat` (
  `ID` smallint(6) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `url` varchar(80) NOT NULL default '',
  `nombre` varchar(80) NOT NULL default '',
  `num` smallint(6) unsigned NOT NULL default '0',
  `nivel` tinyint(3) unsigned NOT NULL default '0',
  `tipo` enum('empresas','docs','cargos') NOT NULL default 'docs',
  `orden` tinyint(3) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `url` (`url`,`nivel`,`tipo`,`orden`,`nombre`,`num`)
) ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;
CREATE TABLE `chats` (
  `chat_ID` smallint(5) unsigned NOT NULL auto_increment,
  `estado` enum('activo','bloqueado','en_proceso','expirado','borrado') character set utf8 NOT NULL default 'en_proceso',
  `pais` varchar(30) character set utf8 default NULL,
  `url` varchar(90) character set utf8 NOT NULL,
  `titulo` varchar(90) character set utf8 NOT NULL,
  `user_ID` mediumint(8) unsigned NOT NULL,
  `admin` varchar(900) NOT NULL default '',
  `acceso_leer` varchar(30) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(30) character set utf8 default 'ciudadanos',
  `acceso_escribir_ex` varchar(30) NOT NULL default '',
  `acceso_cfg_leer` varchar(900) character set utf8 default NULL,
  `acceso_cfg_escribir` varchar(900) character set utf8 default NULL,
  `acceso_cfg_escribir_ex` varchar(900) NOT NULL default '',
  `fecha_creacion` datetime NOT NULL,
  `fecha_last` datetime NOT NULL,
  `dias_expira` smallint(5) unsigned default NULL,
  `url_externa` varchar(500) character set utf8 default NULL,
  `stats_visitas` int(12) unsigned NOT NULL default '0',
  `stats_msgs` int(12) unsigned NOT NULL default '0',
  `GMT` tinyint(2) NOT NULL default '1',
  PRIMARY KEY  (`chat_ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`),
  KEY `pais` (`pais`(1)),
  KEY `acceso_leer` (`acceso_leer`),
  KEY `acceso_escribir` (`acceso_escribir`),
  KEY `acceso_cfg_leer` (`acceso_cfg_leer`(333)),
  KEY `acceso_cfg_escribir` (`acceso_cfg_escribir`(333)),
  KEY `stats_msgs` (`stats_msgs`),
  KEY `fecha_last` (`fecha_last`),
  KEY `acceso_escribir_ex` (`acceso_escribir_ex`),
  KEY `acceso_cfg_escribir_ex` (`acceso_cfg_escribir_ex`)
) ENGINE=MyISAM AUTO_INCREMENT=530 DEFAULT CHARSET=latin1;
CREATE TABLE `chats_msg` (
  `msg_ID` mediumint(8) unsigned NOT NULL auto_increment,
  `chat_ID` smallint(5) unsigned NOT NULL,
  `nick` varchar(32) character set utf8 NOT NULL,
  `msg` varchar(900) character set utf8 NOT NULL,
  `time` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `cargo` tinyint(3) unsigned NOT NULL default '0',
  `user_ID` mediumint(6) unsigned NOT NULL default '0',
  `tipo` enum('m','p','e','c') character set utf8 NOT NULL default 'm',
  `IP` bigint(12) default NULL,
  PRIMARY KEY  (`msg_ID`),
  KEY `chat_ID` (`chat_ID`),
  KEY `nick` (`nick`),
  KEY `time` (`time`),
  KEY `cargo` (`cargo`),
  KEY `user_ID` (`user_ID`),
  KEY `tipo` (`tipo`),
  KEY `msg` (`msg`(333)),
  KEY `IP` (`IP`)
) ENGINE=MyISAM AUTO_INCREMENT=3137737 DEFAULT CHARSET=latin1;
CREATE TABLE `config` (
  `ID` smallint(5) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `dato` varchar(100) NOT NULL default '',
  `valor` text NOT NULL,
  `autoload` enum('si','no') NOT NULL default 'no',
  PRIMARY KEY  (`ID`),
  KEY `dato` (`dato`),
  KEY `autoload` (`autoload`),
  KEY `pais` (`pais`),
  KEY `valor` (`valor`(255))
) ENGINE=MyISAM AUTO_INCREMENT=284 DEFAULT CHARSET=utf8;
CREATE TABLE `cuentas` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `nombre` varchar(25) character set utf8 NOT NULL,
  `user_ID` mediumint(8) NOT NULL default '0',
  `pols` int(10) NOT NULL default '0',
  `nivel` tinyint(3) NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `exenta_impuestos` tinyint(1) NOT NULL default '0',
  `gobierno` enum('true','false') character set utf8 default 'false',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `nombre` (`nombre`),
  KEY `user_ID` (`user_ID`),
  KEY `nivel` (`nivel`),
  KEY `pais` (`pais`)
) ENGINE=MyISAM AUTO_INCREMENT=510 DEFAULT CHARSET=latin1;
CREATE TABLE `docs` (
  `ID` smallint(5) NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `url` varchar(255) character set utf8 NOT NULL default '',
  `title` varchar(255) character set utf8 NOT NULL default '',
  `text` longtext character set utf8 NOT NULL,
  `text_backup` longtext character set utf8 NOT NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `estado` enum('ok','del','borrador') character set utf8 NOT NULL default 'ok',
  `cat_ID` tinyint(3) NOT NULL default '0',
  `acceso_leer` varchar(30) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(30) character set utf8 NOT NULL default 'privado',
  `acceso_cfg_leer` varchar(800) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(800) character set utf8 NOT NULL default '',
  `version` mediumint(9) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `estado` (`estado`),
  KEY `cat_ID` (`cat_ID`),
  KEY `url` (`url`),
  KEY `pais` (`pais`),
  KEY `time` (`time`,`time_last`)
) ENGINE=MyISAM AUTO_INCREMENT=886 DEFAULT CHARSET=latin1;
CREATE TABLE `empresas` (
  `ID` smallint(5) NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `url` varchar(40) character set utf8 NOT NULL default '',
  `nombre` varchar(40) character set utf8 NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `descripcion` text character set utf8 NOT NULL,
  `web` varchar(200) character set utf8 NOT NULL default '',
  `cat_ID` tinyint(3) NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `pv` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`,`cat_ID`),
  KEY `cat_ID` (`cat_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=690 DEFAULT CHARSET=latin1;
CREATE TABLE `empresas_acciones` (
  `ID` int(11) NOT NULL auto_increment,
  `ID_empresa` mediumint(9) unsigned NOT NULL default '0',
  `pais` varchar(30) default NULL,
  `nick` varchar(300) character set utf8 collate utf8_spanish_ci NOT NULL,
  `num_acciones` int(11) NOT NULL default '100',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `examenes` (
  `ID` mediumint(9) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `titulo` varchar(255) default NULL,
  `descripcion` text,
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `cargo_ID` smallint(5) NOT NULL default '0',
  `nota` varchar(5) NOT NULL default '5.0',
  `num_preguntas` smallint(5) unsigned NOT NULL default '10',
  `ID_old` mediumint(8) unsigned default NULL,
  PRIMARY KEY  (`ID`),
  KEY `titulo` (`titulo`),
  KEY `nota` (`nota`),
  KEY `pais` (`pais`),
  KEY `cargo_ID` (`cargo_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=248 DEFAULT CHARSET=utf8;
CREATE TABLE `examenes_preg` (
  `ID` int(11) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `examen_ID` smallint(5) unsigned NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `pregunta` text NOT NULL,
  `respuestas` text NOT NULL,
  `tiempo` varchar(6) NOT NULL default '',
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`),
  KEY `examen_ID` (`examen_ID`),
  KEY `user_ID` (`user_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3026 DEFAULT CHARSET=utf8;
CREATE TABLE `expulsiones` (
  `ID` smallint(5) NOT NULL auto_increment,
  `user_ID` mediumint(8) NOT NULL default '0',
  `autor` mediumint(8) NOT NULL default '0',
  `expire` datetime NOT NULL default '0000-00-00 00:00:00',
  `razon` varchar(150) NOT NULL,
  `estado` enum('activo','inactivo','expulsado','cancelado') NOT NULL default 'activo',
  `tiempo` varchar(20) NOT NULL default '0',
  `IP` varchar(12) NOT NULL default '0',
  `cargo` tinyint(3) unsigned NOT NULL default '12',
  `motivo` text NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `user_ID` (`user_ID`),
  KEY `estado` (`estado`),
  KEY `IP` (`IP`)
) ENGINE=MyISAM AUTO_INCREMENT=1290 DEFAULT CHARSET=latin1;
CREATE TABLE `grupos` (
  `grupo_ID` int(11) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `nombre` varchar(255) NOT NULL default '',
  `num` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`grupo_ID`),
  KEY `num` (`num`)
) ENGINE=MyISAM AUTO_INCREMENT=106 DEFAULT CHARSET=utf8;
CREATE TABLE `hechos` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment,
  `pais` varchar(30) character set utf8 default NULL,
  `time` date NOT NULL,
  `nick` varchar(14) character set utf8 NOT NULL default 'GONZO',
  `texto` varchar(2000) character set utf8 NOT NULL,
  `estado` enum('ok','del') character set utf8 NOT NULL default 'ok',
  `time2` datetime NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `time` (`time`,`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=344 DEFAULT CHARSET=latin1;
CREATE TABLE `hispania_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `subforo_ID` mediumint(9) unsigned default NULL,
  `url` varchar(50) NOT NULL default '',
  `title` varchar(50) NOT NULL default '',
  `descripcion` varchar(255) NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(255) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(255) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_escribir_msg` varchar(255) NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir_msg` varchar(900) NOT NULL default '',
  `limite` tinyint(3) unsigned NOT NULL default '8',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=57 DEFAULT CHARSET=latin1;
CREATE TABLE `hispania_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` mediumint(9) NOT NULL default '0',
  `votos_num` mediumint(9) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=4765 DEFAULT CHARSET=utf8;
CREATE TABLE `hispania_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` mediumint(9) NOT NULL default '0',
  `votos_num` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `foro_ID` (`hilo_ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=40506 DEFAULT CHARSET=utf8;
CREATE TABLE `kicks` (
  `ID` mediumint(9) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `user_ID` mediumint(9) unsigned NOT NULL default '0',
  `autor` mediumint(8) unsigned NOT NULL default '0',
  `expire` datetime NOT NULL default '0000-00-00 00:00:00',
  `razon` varchar(160) NOT NULL default '',
  `estado` enum('activo','inactivo','expulsado','cancelado') NOT NULL default 'activo',
  `tiempo` varchar(20) NOT NULL default '0',
  `IP` varchar(12) NOT NULL default '0',
  `cargo` tinyint(3) unsigned NOT NULL default '0',
  `motivo` text NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`,`user_ID`,`estado`,`expire`)
) ENGINE=MyISAM AUTO_INCREMENT=346 DEFAULT CHARSET=utf8;
CREATE TABLE `log` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `nick` varchar(20) NOT NULL default '',
  `accion` text NOT NULL,
  `accion_a` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`),
  KEY `user_ID` (`user_ID`),
  KEY `time` (`time`)
) ENGINE=MyISAM AUTO_INCREMENT=7765 DEFAULT CHARSET=utf8;
CREATE TABLE `mapa` (
  `ID` smallint(5) unsigned NOT NULL auto_increment,
  `pais` varchar(30) character set utf8 default NULL,
  `pos_x` tinyint(2) NOT NULL default '1',
  `pos_y` tinyint(2) NOT NULL default '1',
  `size_x` tinyint(2) NOT NULL default '1',
  `size_y` tinyint(2) NOT NULL default '1',
  `user_ID` mediumint(8) NOT NULL default '1',
  `nick` varchar(255) default NULL,
  `link` varchar(90) NOT NULL default '',
  `text` varchar(90) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `pols` mediumint(8) NOT NULL default '0',
  `color` char(3) NOT NULL default '',
  `estado` enum('p','v','e') NOT NULL default 'p',
  `superficie` smallint(4) NOT NULL default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=899 DEFAULT CHARSET=latin1;
CREATE TABLE `mensajes` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `envia_ID` mediumint(8) unsigned NOT NULL default '0',
  `recibe_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `leido` enum('0','1') NOT NULL default '0',
  `cargo` smallint(5) NOT NULL default '0',
  `recibe_masivo` varchar(10) NOT NULL default '',
  PRIMARY KEY  (`ID`),
  KEY `envia_ID` (`envia_ID`),
  KEY `recibe_ID` (`recibe_ID`),
  KEY `leido` (`leido`),
  KEY `time` (`time`)
) ENGINE=MyISAM AUTO_INCREMENT=185105 DEFAULT CHARSET=utf8;
CREATE TABLE `notificaciones` (
  `noti_ID` int(11) unsigned NOT NULL auto_increment,
  `time` timestamp NULL default CURRENT_TIMESTAMP,
  `emisor` enum('sistema','15M','Hispania','RSSV') NOT NULL default 'sistema',
  `visto` enum('true','false') NOT NULL default 'false',
  `user_ID` mediumint(8) NOT NULL default '0',
  `texto` varchar(60) NOT NULL default '',
  `url` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`noti_ID`),
  KEY `time` (`time`),
  KEY `visto` (`visto`),
  KEY `user_ID` (`user_ID`),
  KEY `url` (`url`),
  KEY `texto` (`texto`)
) ENGINE=MyISAM AUTO_INCREMENT=67834 DEFAULT CHARSET=utf8;
CREATE TABLE `partidos` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `ID_presidente` mediumint(8) unsigned NOT NULL default '0',
  `fecha_creacion` datetime NOT NULL default '0000-00-00 00:00:00',
  `siglas` varchar(20) default NULL,
  `nombre` varchar(50) default NULL,
  `descripcion` text,
  `estado` enum('ok') NOT NULL default 'ok',
  `ID_old` smallint(6) unsigned default NULL,
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`),
  KEY `ID_presidente` (`ID_presidente`),
  KEY `siglas` (`siglas`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=39 DEFAULT CHARSET=utf8;
CREATE TABLE `partidos_listas` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `ID_partido` mediumint(8) default '0',
  `user_ID` mediumint(9) unsigned default '0',
  `orden` smallint(5) default '0',
  PRIMARY KEY  (`ID`),
  KEY `ID_partido` (`ID_partido`),
  KEY `user_ID` (`user_ID`),
  KEY `orden` (`orden`),
  KEY `pais` (`pais`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;
CREATE TABLE `plataformas` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment,
  `estado` enum('pendiente','ok','no') default 'pendiente',
  `pais` varchar(255) default NULL,
  `asamblea` enum('true','false') default 'false',
  `economia` enum('true','false') default 'true',
  `user_ID` mediumint(8) unsigned default NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `descripcion` text,
  `participacion` mediumint(8) unsigned default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `pol_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `url` varchar(50) NOT NULL default '',
  `title` varchar(50) NOT NULL default '',
  `descripcion` varchar(255) NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(255) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(255) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
CREATE TABLE `pol_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` mediumint(9) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=5995 DEFAULT CHARSET=latin1;
CREATE TABLE `pol_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` mediumint(9) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `foro_ID` (`hilo_ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=56233 DEFAULT CHARSET=latin1;
CREATE TABLE `pujas` (
  `ID` mediumint(9) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `mercado_ID` smallint(5) default NULL,
  `user_ID` mediumint(9) unsigned default NULL,
  `pols` mediumint(8) unsigned default NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`),
  KEY `mercado_ID` (`mercado_ID`),
  KEY `user_ID` (`user_ID`),
  KEY `time` (`time`)
) ENGINE=MyISAM AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;
CREATE TABLE `referencias` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `user_ID` mediumint(8) NOT NULL default '0',
  `IP` varchar(10) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `referer` varchar(255) NOT NULL default '',
  `pagado` enum('0','1') NOT NULL default '0',
  `new_user_ID` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `IP` (`IP`),
  KEY `user_ID` (`user_ID`),
  KEY `pagado` (`pagado`)
) ENGINE=MyISAM AUTO_INCREMENT=9529 DEFAULT CHARSET=latin1;
CREATE TABLE `rssv_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `subforo_ID` smallint(5) unsigned default NULL,
  `url` varchar(50) character set utf8 NOT NULL default '',
  `title` varchar(50) character set utf8 NOT NULL default '',
  `descripcion` varchar(255) character set utf8 NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') character set utf8 NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(900) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(900) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_escribir_msg` varchar(900) NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir_msg` varchar(900) NOT NULL default '',
  `limite` tinyint(3) unsigned NOT NULL default '8',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`),
  KEY `time` (`time`),
  KEY `acceso_leer` (`acceso_leer`(333)),
  KEY `acceso_escribir` (`acceso_escribir`(333)),
  KEY `acceso_cfg_leer` (`acceso_cfg_leer`(333)),
  KEY `acceso_cfg_escribir` (`acceso_cfg_escribir`(333))
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=latin1;
CREATE TABLE `rssv_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` smallint(6) NOT NULL default '0',
  `votos_num` mediumint(9) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=328 DEFAULT CHARSET=latin1;
CREATE TABLE `rssv_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` smallint(6) NOT NULL default '0',
  `votos_num` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`),
  KEY `hilo_ID` (`hilo_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1942 DEFAULT CHARSET=latin1;
CREATE TABLE `stats` (
  `stats_ID` smallint(5) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `ciudadanos` smallint(5) unsigned NOT NULL default '0',
  `nuevos` smallint(5) unsigned NOT NULL default '0',
  `pols` int(10) NOT NULL default '0',
  `pols_cuentas` int(10) NOT NULL default '0',
  `transacciones` smallint(5) unsigned NOT NULL default '0',
  `hilos_msg` smallint(5) unsigned NOT NULL default '0',
  `pols_gobierno` int(10) NOT NULL default '0',
  `partidos` tinyint(3) unsigned NOT NULL default '0',
  `frase` smallint(5) unsigned NOT NULL default '0',
  `empresas` smallint(5) unsigned NOT NULL default '0',
  `eliminados` smallint(5) unsigned NOT NULL default '0',
  `mapa` tinyint(3) unsigned NOT NULL default '0',
  `mapa_vende` tinyint(3) unsigned NOT NULL default '0',
  `24h` smallint(5) unsigned NOT NULL default '0',
  `confianza` smallint(5) NOT NULL,
  `autentificados` mediumint(9) default NULL,
  PRIMARY KEY  (`stats_ID`),
  KEY `time` (`time`),
  KEY `pais` (`pais`)
) ENGINE=MyISAM AUTO_INCREMENT=2841 DEFAULT CHARSET=latin1;
CREATE TABLE `transacciones` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `pols` int(10) NOT NULL default '0',
  `emisor_ID` mediumint(8) NOT NULL default '0',
  `receptor_ID` mediumint(8) NOT NULL default '0',
  `concepto` varchar(90) character set utf8 NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ID`),
  KEY `emisor_ID` (`emisor_ID`),
  KEY `receptor_ID` (`receptor_ID`),
  KEY `time` (`time`)
) ENGINE=MyISAM AUTO_INCREMENT=59750 DEFAULT CHARSET=latin1;
CREATE TABLE `users` (
  `ID` mediumint(8) unsigned NOT NULL auto_increment,
  `nick` varchar(18) NOT NULL default '',
  `lang` varchar(5) default NULL,
  `pais` varchar(30) default NULL,
  `estado` enum('turista','ciudadano','expulsado','validar') NOT NULL default 'validar',
  `nivel` tinyint(3) unsigned NOT NULL default '1',
  `cargo` tinyint(3) unsigned NOT NULL default '0',
  `cargos` varchar(400) NOT NULL default '',
  `grupos` varchar(400) NOT NULL default '',
  `examenes` varchar(400) NOT NULL default '',
  `voto_confianza` smallint(5) NOT NULL default '0',
  `partido_afiliado` mediumint(9) unsigned NOT NULL default '0',
  `online` int(10) unsigned NOT NULL default '0',
  `visitas` mediumint(8) unsigned NOT NULL default '0',
  `paginas` int(10) unsigned NOT NULL default '0',
  `pols` int(10) NOT NULL default '0',
  `email` varchar(255) NOT NULL default '',
  `fecha_registro` datetime NOT NULL default '0000-00-00 00:00:00',
  `fecha_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `fecha_init` datetime NOT NULL default '0000-00-00 00:00:00',
  `rechazo_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `fecha_legal` datetime NOT NULL default '0000-00-00 00:00:00',
  `reset_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `nickchange_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `pass` varchar(255) NOT NULL default '',
  `pass2` varchar(255) NOT NULL default '',
  `api_pass` varchar(16) NOT NULL default '0',
  `api_num` smallint(5) NOT NULL default '0',
  `num_elec` tinyint(3) unsigned NOT NULL default '0',
  `SC` enum('true','false') NOT NULL default 'false',
  `ser_SC` enum('true','false') NOT NULL default 'false',
  `nota` decimal(3,1) NOT NULL default '0.0',
  `ref` varchar(25) NOT NULL default '',
  `ref_num` mediumint(8) unsigned NOT NULL default '0',
  `IP` varchar(12) NOT NULL default '0',
  `avatar` enum('true','false') NOT NULL default 'false',
  `text` varchar(2300) NOT NULL default '',
  `nav` varchar(500) NOT NULL,
  `avatar_localdir` varchar(100) NOT NULL,
  `host` varchar(150) NOT NULL,
  `hosts` text,
  `IP_proxy` varchar(150) NOT NULL,
  `geo` varchar(200) NOT NULL,
  `x` decimal(10,3) default NULL,
  `y` decimal(10,3) default NULL,
  `dnie` enum('true','false') default 'false',
  `dnie_check` varchar(400) default NULL,
  `bando` varchar(255) default NULL,
  `nota_SC` varchar(500) NOT NULL default '',
  `traza` varchar(600) NOT NULL default '',
  `datos` varchar(9999) NOT NULL default '',
  `donacion` mediumint(9) unsigned default NULL,
  `temp` int(11) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `nick` (`nick`),
  KEY `pais` (`pais`),
  KEY `fecha_last` (`fecha_last`),
  KEY `estado` (`estado`),
  KEY `voto_confianza` (`voto_confianza`),
  KEY `IP` (`IP`),
  KEY `pass` (`pass`),
  KEY `cargo` (`cargo`),
  KEY `grupos` (`grupos`(333)),
  KEY `cargos` (`cargos`(333)),
  KEY `examenes` (`examenes`(333)),
  KEY `x` (`x`),
  KEY `y` (`y`)
) ENGINE=MyISAM AUTO_INCREMENT=212309 DEFAULT CHARSET=utf8;
CREATE TABLE `votacion` (
  `ID` smallint(5) NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `pregunta` varchar(255) NOT NULL default '',
  `descripcion` text NOT NULL,
  `respuestas` text NOT NULL,
  `respuestas_desc` text NOT NULL,
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_expire` datetime NOT NULL default '0000-00-00 00:00:00',
  `user_ID` mediumint(8) NOT NULL default '0',
  `estado` enum('ok','end','borrador') NOT NULL default 'borrador',
  `num` smallint(5) NOT NULL default '0',
  `tipo` enum('sondeo','referendum','parlamento','destituir','otorgar','cargo','elecciones') NOT NULL default 'sondeo',
  `debate_url` varchar(255) NOT NULL default '',
  `acceso_votar` varchar(30) NOT NULL default 'ciudadanos_pais',
  `acceso_cfg_votar` varchar(900) NOT NULL default '',
  `acceso_ver` varchar(255) NOT NULL default 'anonimos',
  `acceso_cfg_ver` varchar(900) NOT NULL default '',
  `ejecutar` text NOT NULL,
  `votos_expire` smallint(5) unsigned NOT NULL default '0',
  `tipo_voto` enum('estandar','3puntos','5puntos','8puntos','multiple') NOT NULL default 'estandar',
  `privacidad` enum('true','false') NOT NULL default 'true',
  `aleatorio` enum('true','false') NOT NULL default 'false',
  `duracion` mediumint(9) unsigned NOT NULL default '0',
  `num_censo` int(11) unsigned default NULL,
  `cargo_ID` smallint(6) unsigned default NULL,
  PRIMARY KEY  (`ID`),
  KEY `pais` (`pais`),
  KEY `time_expire` (`time_expire`),
  KEY `estado` (`estado`),
  KEY `tipo` (`tipo`),
  KEY `num` (`num`),
  KEY `votos_expire` (`votos_expire`)
) ENGINE=MyISAM AUTO_INCREMENT=2579 DEFAULT CHARSET=utf8;
CREATE TABLE `votacion_votos` (
  `ID` int(11) unsigned NOT NULL auto_increment,
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `ref_ID` smallint(5) unsigned NOT NULL default '0',
  `time` datetime default NULL,
  `voto` varchar(300) character set utf8 NOT NULL default '0',
  `validez` enum('true','false') character set utf8 NOT NULL default 'true',
  `autentificado` enum('true','false') default 'false',
  `mensaje` varchar(500) NOT NULL default '',
  `comprobante` varchar(600) character set utf8 default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ref_ID` (`ref_ID`),
  KEY `user_ID` (`user_ID`),
  KEY `voto` (`voto`),
  KEY `validez` (`validez`),
  KEY `time` (`time`)
) ENGINE=MyISAM AUTO_INCREMENT=94894 DEFAULT CHARSET=latin1;
CREATE TABLE `votos` (
  `voto_ID` int(11) unsigned NOT NULL auto_increment,
  `pais` varchar(30) default NULL,
  `item_ID` int(11) unsigned NOT NULL default '0',
  `emisor_ID` mediumint(8) unsigned NOT NULL default '0',
  `voto` tinyint(3) NOT NULL,
  `tipo` enum('confianza','hilos','msg') character set utf8 NOT NULL default 'confianza',
  `time` datetime NOT NULL,
  PRIMARY KEY  (`voto_ID`),
  KEY `tipo` (`tipo`),
  KEY `emisor_ID` (`emisor_ID`),
  KEY `item_ID` (`item_ID`),
  KEY `pais` (`pais`),
  KEY `voto` (`voto`)
) ENGINE=MyISAM AUTO_INCREMENT=86409 DEFAULT CHARSET=latin1;
CREATE TABLE `vp_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `subforo_ID` smallint(5) unsigned default NULL,
  `url` varchar(50) character set utf8 NOT NULL default '',
  `title` varchar(50) character set utf8 NOT NULL default '',
  `descripcion` varchar(255) character set utf8 NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '1',
  `estado` enum('ok','eliminado') character set utf8 NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(900) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(900) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_escribir_msg` varchar(900) NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir_msg` varchar(900) NOT NULL default '',
  `limite` tinyint(3) unsigned NOT NULL default '8',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`),
  KEY `time` (`time`),
  KEY `acceso_leer` (`acceso_leer`(333)),
  KEY `acceso_escribir` (`acceso_escribir`(333)),
  KEY `acceso_cfg_leer` (`acceso_cfg_leer`(333)),
  KEY `acceso_cfg_escribir` (`acceso_cfg_escribir`(333))
) ENGINE=MyISAM AUTO_INCREMENT=61 DEFAULT CHARSET=latin1;
CREATE TABLE `vp_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` smallint(6) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=10213 DEFAULT CHARSET=latin1;
CREATE TABLE `vp_foros_msg` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) unsigned NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) unsigned NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` smallint(6) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`),
  KEY `hilo_ID` (`hilo_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=98144 DEFAULT CHARSET=latin1;
CREATE TABLE `vulcan_foros` (
  `ID` smallint(5) NOT NULL auto_increment,
  `url` varchar(50) NOT NULL default '',
  `title` varchar(50) NOT NULL default '',
  `descripcion` varchar(255) NOT NULL default '',
  `acceso` tinyint(3) unsigned NOT NULL default '1',
  `time` smallint(3) NOT NULL default '20',
  `estado` enum('ok') NOT NULL default 'ok',
  `acceso_msg` tinyint(3) unsigned NOT NULL default '1',
  `acceso_leer` varchar(255) character set utf8 NOT NULL default 'anonimos',
  `acceso_escribir` varchar(255) character set utf8 NOT NULL default 'ciudadanos',
  `acceso_cfg_leer` varchar(900) character set utf8 NOT NULL default '',
  `acceso_cfg_escribir` varchar(900) character set utf8 NOT NULL default '',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;
CREATE TABLE `vulcan_foros_hilos` (
  `ID` mediumint(8) NOT NULL auto_increment,
  `sub_ID` smallint(5) NOT NULL default '0',
  `url` varchar(80) NOT NULL default '',
  `user_ID` mediumint(8) NOT NULL default '0',
  `title` varchar(80) NOT NULL default '',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `time_last` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '0',
  `num` smallint(5) NOT NULL default '0',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `votos` mediumint(9) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `url` (`url`),
  KEY `sub_ID` (`sub_ID`),
  KEY `time_last` (`time_last`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=829 DEFAULT CHARSET=latin1;
CREATE TABLE `vulcan_foros_msg` (
  `ID` int(10) NOT NULL auto_increment,
  `hilo_ID` mediumint(8) NOT NULL default '0',
  `user_ID` mediumint(8) NOT NULL default '0',
  `time` datetime NOT NULL default '0000-00-00 00:00:00',
  `text` text NOT NULL,
  `cargo` tinyint(3) NOT NULL default '1',
  `estado` enum('ok','borrado') NOT NULL default 'ok',
  `time2` datetime NOT NULL default '0000-00-00 00:00:00',
  `votos` mediumint(9) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  KEY `foro_ID` (`hilo_ID`),
  KEY `time` (`time`),
  KEY `estado` (`estado`)
) ENGINE=MyISAM AUTO_INCREMENT=4808 DEFAULT CHARSET=latin1;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
