CREATE TABLE `msg` (
	`msg_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`channel` DECIMAL(10,0) UNSIGNED NULL DEFAULT NULL,
	`date_create` DATETIME NULL DEFAULT NULL,
	`date_consensus` DATETIME NULL DEFAULT NULL,
	`state` VARCHAR(50) NULL DEFAULT NULL,
	`text` VARCHAR(900) NULL DEFAULT NULL,
	`user_id` VARCHAR(900) NULL DEFAULT NULL,
	`ip` VARCHAR(50) NULL DEFAULT NULL,
	`num` DECIMAL(10,0) UNSIGNED NULL DEFAULT NULL,
	`points` MEDIUMINT(9) NULL DEFAULT NULL,
	PRIMARY KEY (`msg_id`),
	INDEX `channel` (`channel`)
)
ENGINE=InnoDB;